### ISSUE TITLE
undefined: Asset

### ISSUE THREAD

**Issue by svenfinke** [3stadt/presla#58]
It seems like there is some dependency missing.. I get the following errors:

![bildschirmfoto 2018-03-28 um 11 39 18](https://user-images.githubusercontent.com/564499/38021267-af7baa82-327c-11e8-917a-01da13c2ed57.png)

**Comment by 3stadt** [comment]
Did you run `make deps` and `make bindata` or `make bindata-debug`?

**Comment by svenfinke** [comment]
Of course. Not.... -.- Yeah, That will probably solve the issue. I'll try again when that is finished, and close the issue then.

**Comment by svenfinke** [comment]
Yeah, it worked just fine after running make... :D
